SELECT *
	FROM CLIENTES
	ORDER BY DIRECCION;

SELECT *
	FROM CLIENTES
	ORDER BY DIRECCION, NOMBRE;

SELECT *
	FROM CLIENTES
	ORDER BY DIRECCION DESC, NOMBRE ASC;

SELECT *
	FROM CLIENTES
	ORDER BY DIRECCION DESC, NOMBRE DESC;
	
SELECT	NOMBRE,
		DIRECCION,
		NROCOMPRAS,
		MONTOCOMPRAS
		FROM	CLIENTES
		ORDER BY 2, 1;
		
SELECT	NOMBRE AS NOMBRE_CLIENTE,
		DIRECCION AS DIRECCION_CLIENTE,
		NROCOMPRAS NUMERO_DE_COMPRAS,
		MONTOCOMPRAS MONTO_COMPRAS
		FROM	CLIENTES
		ORDER BY DIRECCION_CLIENTE, NOMBRE_CLIENTE;

SELECT	*
	FROM CLIENTES
	ORDER BY ULTIMACOMPRA;

SELECT	*
	FROM CLIENTES
	ORDER BY ULTIMACOMPRA NULLS FIRST;

SELECT	*
	FROM CLIENTES
	WHERE IDCLIENTE = :codCliente;