CREATE OR REPLACE FUNCTION F_VALIDA_DOCUMENTO (
	p_tipo_doc IN CHAR,
	p_nro_doc IN VARCHAR2
) RETURN NUMBER AS

	var_n_registros	NUMBER;

BEGIN
	SELECT COUNT(*) INTO var_n_registros
		FROM CLIENTES
		WHERE TIPODOCUMENTO = p_tipo_doc
		AND NRODOCUMENTO = p_nro_doc;
	
	RETURN var_n_registros;
	
END F_VALIDA_DOCUMENTO;


SELECT F_VALIDA_DOCUMENTO('1', '123456') FROM dual; 


CREATE OR REPLACE FUNCTION F_VALIDA_TELEFONO (
	p_telefono IN VARCHAR2
) RETURN NUMBER AS

	var_n_registros	NUMBER;

BEGIN
	SELECT COUNT(*) INTO var_n_registros
		FROM CLIENTES
		WHERE TELEFONO = p_telefono;
	
	RETURN var_n_registros;
	
END F_VALIDA_TELEFONO;

SELECT F_VALIDA_TELEFONO('123456') FROM dual;