SELECT *
	FROM CLIENTES;
	
SELECT	NOMBRE,
		NROCOMPRAS,
		MONTOCOMPRAS
		FROM	CLIENTES;
		
SELECT	NOMBRE AS NOMBRE_CLIENTE,
		NROCOMPRAS NUMERO_DE_COMPRAS,
		MONTOCOMPRAS MONTO_COMPRAS
		FROM	CLIENTES;

SELECT	NOMBRE,
		TIPODOCUMENTO || '-' || NRODOCUMENTO AS DOCUMENTO 
		FROM CLIENTES;

SELECT	PRECIONORMAL,
		PRECIONORMAL - DESCUENTO PRECIOCONDESCUENTO,
		(PRECIONORMAL - DESCUENTO) * TASAIMPUESTO/100 AS IMPUESTOS,
		(1 + TASAIMPUESTO/100) * (PRECIONORMAL - DESCUENTO) AS PRECIOCONIMPUESTO 
	FROM LINEAFACTURA;
	
SELECT	PRECIONORMAL,
		PRECIONORMAL - DESCUENTO PRECIOCONDESCUENTO,
		(PRECIONORMAL - DESCUENTO) * TASAIMPUESTO/100 AS IMPUESTOS,
		(1 + TASAIMPUESTO/100) * (PRECIONORMAL - DESCUENTO) AS PRECIOCONIMPUESTO 
	FROM LINEAFACTURA
	WHERE IDFACTURA = 2;
	
SELECT	PRECIONORMAL,
		PRECIONORMAL - DESCUENTO PRECIOCONDESCUENTO,
		(PRECIONORMAL - DESCUENTO) * TASAIMPUESTO/100 AS IMPUESTOS,
		(1 + TASAIMPUESTO/100) * (PRECIONORMAL - DESCUENTO) AS PRECIOCONIMPUESTO 
	FROM LINEAFACTURA
	WHERE IDFACTURA = 2 OR IDFACTURA = 3;
	
SELECT	PRECIONORMAL,
		PRECIONORMAL - DESCUENTO PRECIOCONDESCUENTO,
		(PRECIONORMAL - DESCUENTO) * TASAIMPUESTO/100 AS IMPUESTOS,
		(1 + TASAIMPUESTO/100) * (PRECIONORMAL - DESCUENTO) AS PRECIOCONIMPUESTO 
	FROM LINEAFACTURA
	WHERE IDFACTURA IN (2, 3, 4);

SELECT	*
	FROM CLIENTES
	WHERE NROCOMPRAS >= 1;

SELECT	*
	FROM CLIENTES
	WHERE NROCOMPRAS >= 1
	AND MONTOCOMPRAS >= 10;

SELECT	*
	FROM FACTURA
	WHERE MONTONETO BETWEEN 10 AND 20;

SELECT *
	FROM  PRODUCTO
	WHERE DESCRIPCIONCORTA = 'Lápiz';

SELECT *
	FROM  PRODUCTO
	WHERE DESCRIPCIONCORTA like '%por%';

SELECT *
	FROM PRODUCTO
	WHERE ULTIMAVENTA IS NULL;

SELECT *
	FROM  CLIENTES
	WHERE ULTIMACOMPRA IS NOT NULL;

SELECT DIRECCION 
	FROM CLIENTES;

SELECT DISTINCT DIRECCION 
	FROM CLIENTES;